project:
  name: quickstart-datalake-foundation
  owner: quickstart@amazon.com
  package_lambda: false
  regions:
  - us-east-1
  - us-east-2
  - us-west-2
  s3_bucket: ''
tests:
  single-node-with-wizard:
    parameters:
      AvailabilityZones: $[taskcat_getaz_2]
      ElasticsearchNodeCount: '1'
      KeyPairName: $[taskcat_getkeypair]
      KinesisDataStreamName: streaming-submissions
      KinesisDataStreamS3Prefix: streaming-submissions
      NotebookInstanceName: SageMakerNotebookInstTestDev
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      RedshiftDatabaseName: testdb
      RedshiftDatabasePort: '5439'
      RedshiftNodeType: dc2.large
      RedshiftNumberOfNodes: '1'
      RedshiftPassword: $[alfred_genpass_16]
      RedshiftUsername: datalake
      RemoteAccessCIDR: 89.65.65.154/32
      VPCDefinition: QuickstartDefault
    regions:
    - us-east-1
    s3_bucket: ''
    template: templates/data-lake-master.template.yaml
